project_id = "hjupkurtumzqrwoytjnn"

[functions.transcribe-audio]
verify_jwt = false

[functions.process-visit-summary]
verify_jwt = false

[functions.generate-previsit-education]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true
